### ISSUE TITLE
Include the GCP SDK so that run-job can execute against Google Kubernetes Engine

### ISSUE THREAD

**Issue by alexellis** [alexellis/run-job#30]
## Description

Include the GCP SDK so that run-job can execute against Google Kubernetes Engine

## Why is this needed?

run-job runs out of cluster, and GCP requires an additional import to work.

Generally, it means just adding this to main.go

```golang
	// required to authenticate against GKE clusters
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

See also: https://github.com/openfaas/faas-netes/blob/master/main.go

I'd like someone to test this against a real GKE cluster as part of the PR submission.

**Comment by alexellis** [comment]
@Jasstkn thoughts on contributing this? 🙂

**Comment by Jasstkn** [comment]
Unfortunately, I don't have an access to up & running GKE cluster. Only EKS 😅

**Comment by alexellis** [comment]
As I understand it - the first control plane is free - and there's 300 USD of credit when signing up. A single preemptable VM costs ~ 6-8 USD / mo.

https://cloud.google.com/free

We could try this out of cluster on EKS though - it may have a similar issue?

**Comment by Jasstkn** [comment]
> As I understand it - the first control plane is free - and there's 300 USD of credit when signing up. A single preemptable VM costs ~ 6-8 USD / mo.
> 
> https://cloud.google.com/free
> 
> We could try this out of cluster on EKS though - it may have a similar issue?

Yep, I'm well aware of the GCP pricing - have been working with it for years. Let me quickly check it on EKS and over the weekend I'll try to setup gke.

**Comment by Jasstkn** [comment]
No errors in EKS.

```
Created job cows.default (232d5ccd-e49a-4836-931a-9897dab48663)
..
Job cows.default (232d5ccd-e49a-4836-931a-9897dab48663) succeeded 
Deleted job cows

Recorded: 2023-03-31 08:44:27.920483 +0000 UTC


                       _,-----.
         _,------.__,-'        `.  .            .
      .-'                        `//__          \\
     |                           ((___`-_____    ))
     |                            \_alf)     \`=:'
     |                               `=|      |=,'
    /                                  | O   (|
   /  /\                               |      |
  /  /  \    .                          \     |
 |  /   /|  / `--.   ___            __,,-.    |
 | /   //  /      `-'   \  ,_    /''     |  o o|
/ |   | |  |             \ \ `.  |        ``--'
mmm   | |  |              \ \ |  |
      | |\ |              |  ||  |
      | | ||              / / `. )
       \ \ \\            / /   | |
        |_| ||          / /    | |
            |_\         \_|    |  \
                                \__\
```

**Comment by alexellis** [comment]
Thanks and that's an oddly satisfying ASCII :cow2:

**Comment by alexellis** [comment]
I'll just add the code myself.

Perhaps @jsiebens would be interested in trying it out as a GCP user?

**Comment by jsiebens** [comment]
```
jsiebens@orion:~/tmp$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.9-gke.3200


jsiebens@orion:~/tmp$ run-job -f cows.yaml 
Created job cows.default (6b4f6fee-6a89-4739-ab4b-7fc036824b81)
......
Job cows.default (6b4f6fee-6a89-4739-ab4b-7fc036824b81) succeeded 
Deleted job cows

Recorded: 2023-04-01 14:35:54.141527982 +0000 UTC

         (__)
         (oo)
  /-------\/
 / |     ||
*  ||----||
   OO    OO
```

Looks good :+1:

**Comment by alexellis** [comment]
Thank you @jsiebens 💪
