### ISSUE TITLE
[Feature] Support job creation from existing resources (--from cronjob/name)

### ISSUE THREAD

**Issue by Baldinof** [alexellis/run-job#50]
Hello!

Thanks for this project, I wonder if you would accept a pull request implementing the same behavior of `kubectl create job --from cronjob/name`?

It could go further with supporting `--from deployment|pod/name` and allows to override the args of the pod template.

Examples:

```
run-job --from cronjob/my-cronjob
run-job --from deployment/my-app -out report.txt -- my-app my-command
```

This would allow to run one-off script without having to create a manifest file.

**Comment by alexellis** [comment]
Hi, I'm not sure this is something we would like to support.

Can you please explain/defend the suggestion? At the moment I don't see from your notes how this solves any problem, or what use-case you're blocked on.

Alex
